### ISSUE TITLE
Opening or editing less files throws TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by Graloth** [shinnn/vscode-stylelint#131]
Any time I type anything in a .less-file or even open one, vscode throws the error below.
Unsure how to fix this, so any pointers would be more than welcome.

```
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2744 TypeError: Cannot read property '0' of undefined     at LessParser.createRule (/Users/dionsunejensen/.vscode/extensions/shinnn.stylelint-0.31.0/node_modules/postcss-less/dist/less-parser.js:129:39)     at LessParser.ruleEnd (/Users/dionsunejensen/.vscode/extensions/shinnn.stylelint-0.31.0/node_modules/postcss-less/dist/less-parser.js:422:14)     at LessParser.other (/Users/dionsunejensen/.vscode/extensions/shinnn.stylelint-0.31.0/node_modules/postcss-less/dist/less-parser.js:382:36)     at LessParser.loop (/Users/dionsunejensen/.vscode/extensions/shinnn.stylelint-0.31.0/node_modules/postcss-less/node_modules/postcss/lib/parser.js:81:26)     at lessParse (/Users/dionsunejensen/.vscode/extensions/shinnn.stylelint-0.31.0/node_modules/postcss-less/dist/less-parse.js:24:10)     at new LazyResult (/Users/dionsunejensen/.vscode/extensions/shinnn.stylelint-0.31.0/node_modules/postcss/lib/lazy-result.js:66:24)     at Processor.process (/Users/dionsunejensen/.vscode/extensions/shinnn.stylelint-0.31.0/node_modules/postcss/lib/processor.js:117:12)     at getCode.then.code (/Users/dionsunejensen/.vscode/extensions/shinnn.stylelint-0.31.0/node_modules/stylelint/lib/getPostcssResult.js:109:31)     at <anonymous>
e.doShow @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2744
```

**Comment by shinnn** [comment]
Not a vscode-stylelint issue.

**Comment by Graloth** [comment]
Could you point me in the direction that the issue then belongs to? The error only mensions the `shinnn.stylelint-0.31.0` extension.

**Comment by shinnn** [comment]
> The error only mensions the shinnn.stylelint-0.31.0 extension.

Check it again more carefully.

**Comment by Graloth** [comment]
Uninstalling and reinstalling stylelint fixed it.
