### ISSUE TITLE
Support JSON in .stylelintrc

### ISSUE THREAD

**Issue by janmarek** [shinnn/vscode-stylelint#17]
Hi,

I got this error in VS Code

```
YAMLException: unknown escape sequence in "/Users/janmarek/www/shipito-client/.stylelintrc" at line 22, column 43: ... tor-class-pattern": "[a-zA-Z0-9\-]+" ^ at generateError (/Users/janmarek/.vscode/extensions/shinnn.stylelint-0.9.1/node_modules/js-yaml/lib/js-yaml/loader.js:162:10) at throwError (/Users/janmarek/.vscode/extensions/shinnn.stylelint-0.9.1/node_modules/js-yaml/lib/js-yaml/loader.js:168:9) at readDoubleQuotedScalar (/Users/
```

I believe this is caused because this extension assumes that config file is YAML. But it can also be JSON.

Thank you

**Comment by shinnn** [comment]
```js
// ./.stylelintrc: {"foo": "[a-zA-Z0-9\-]+"}

'use strict';

const {lint} = require('stylelint');
lint({code: 'a {}'}).catch(e => console.error(e.message));
```

The code above prints:

```
unknown escape sequence in "/Users/Shinnosuke/github/MyRepositories/stylelint-vscode/.stylelintrc" at line 2, column 22:
      "foo": "[a-zA-Z0-9\-]+"
                         ^
```

So this is not a plugin-specific issue. Report it on the proper issue tracker.
