### ISSUE TITLE
Error: Cannot find module 'postcss-jsx/extract'

### ISSUE THREAD

**Issue by pingshunhuangalex** [shinnn/vscode-stylelint#182]
@shinnn With the latest `1.24.0-insider` update and stylelint `0.36.1`, something suddenly broke and I have no idea what that is cuz everything was fine right before the update. Could you please have a look at what might be causing this issue? Thanks.

```
Error: Cannot find module 'postcss-jsx/extract' at Function.Module._resolveFilename (module.js:470:15) at Function.Module._load (module.js:418:25) at Module.require (module.js:498:17) at require (internal/module.js:20:19) at rules.filter.map.rule (C:\Users\SPHS\.vscode-insiders\extensions\shinnn.stylelint-0.36.1\node_modules\stylelint\node_modules\postcss-syntax\processor.js:9:19) at Array.map (native) at processor (C:\Users\SPHS\.vscode-insiders\extensions\shinnn.stylelint-0.36.1\node_modules\stylelint\node_modules\postcss-syntax\processor.js:6:54) at Object.parse (C:\Users\SPHS\.vscode-insiders\extensions\shinnn.stylelint-0.36.1\node_modules\stylelint\node_modules\postcss-syntax\parse.js:18:9) at new LazyResult (C:\Users\SPHS\.vscode-insiders\extensions\shinnn.stylelint-0.36.1\node_modules\postcss\lib\lazy-result.js:70:24) at Processor.process (C:\Users\SPHS\.vscode-insiders\extensions\shinnn.stylelint-0.36.1\node_modules\postcss\lib\processor....
```

**Comment by shinnn** [comment]
It’s not a vscode-stylelint issue. https://github.com/stylelint/stylelint/issues/3317#issuecomment-390223935 Comment on https://github.com/stylelint/stylelint/issues/3319 to urge the stylelint maintainers to release an actually working version.
