### ISSUE TITLE
Issue with latest version

### ISSUE THREAD

**Issue by braddielman** [shinnn/vscode-stylelint#183]
Running the latest version `0.36.1` of vscode-stylelint and I'm seeing this error whenever I open a file:

```
Error: Cannot find module 'postcss-jsx/extract' at Function.Module._resolveFilename (module.js:470:15)
  at Function.Module._load (module.js:418:25) at Module.require (module.js:498:17)
  at require (internal/module.js:20:19)
  at rules.filter.map.rule (/Users/user_name/.vscode/extensions/shinnn.stylelint-0.36.1/node_modules/stylelint/node_modules/postcss-syntax/processor.js:9:19)
  at Array.map (native) at processor (/Users/user_name/.vscode/extensions/shinnn.stylelint-0.36.1/node_modules/stylelint/node_modules/postcss-syntax/processor.js:6:54)
  at Object.parse (/Users/user_name/.vscode/extensions/shinnn.stylelint-0.36.1/node_modules/stylelint/node_modules/postcss-syntax/parse.js:18:9)
  at new LazyResult (/Users/user_name/.vscode/extensions/shinnn.stylelint-0.36.1/node_modules/postcss/lib/lazy-result.js:70:24)
  at Processor.process (/Users/user_name/.vscode/extensions/shinnn.stylelint-0.36.1/node_modules/postcss/lib/processor.js:117:12)
```

**Comment by shinnn** [comment]
https://github.com/shinnn/vscode-stylelint/issues/182#issuecomment-390665800
