### ISSUE TITLE
[0.36.x] error when using stylus in .vue files

### ISSUE THREAD

**Issue by beeplin** [shinnn/vscode-stylelint#186]
```txt
Error: Cannot find module 'postcss-stylus' 
at Function.Module._resolveFilename (module.js:470:15)
at Function.Module._load (module.js:418:25) 
at Module.require (module.js:498:17) 
at require (internal/module.js:20:19) 
at requireSyntax (C:\Users\beep\.vscode\extensions\shinnn.stylelint-0.36.2\node_modules\postcss-syntax\get-syntax.js:26:19) 
at getSyntax (C:\Users\beep\.vscode\extensions\shinnn.stylelint-0.36.2\node_modules\postcss-syntax\get-syntax.js:41:10) 
at LocalFixer.parse (C:\Users\beep\.vscode\extensions\shinnn.stylelint-0.36.2\node_modules\postcss-syntax\parse-style.js:54:34) 
at parseStyle (C:\Users\beep\.vscode\extensions\shinnn.stylelint-0.36.2\node_modules\postcss-syntax\parse-style.js:89:39) 
at styles.sort.forEach.style (C:\Users\beep\.vscode\extensions\shinnn.stylelint-0.36.2\node_modules\postcss-syntax\parse-style.js:104:17) 
at Array.forEach (native)
```

stylelint cannot handle stylus, but when we have `<style lang="stylus">` in a .vue file, it simply gets the name `stylus` and tries to require('postcss-stylus'), which is not existing:

```js
# postcss-syntax/get-syntax.js:18-27
function requireSyntax (lang) {
	if (/^css$/i.test(lang)) {
		return cssSyntax();
	} else if (/^sugarss$/i.test(lang)) {
		lang = "sugarss";
	} else {
		lang = lang.toLowerCase().replace(/^(postcss-)?/i, "postcss-");
	}
	return normalize(require(lang));
}
```

**Comment by beeplin** [comment]
oops, this bug is from upstream `stylelint`. Will open an issue there.

**Comment by shinnn** [comment]
No problem. Thanks for the report, @beeplin.
