### ISSUE TITLE
Latest update generates "Error: Cannot find module 'postcss-xml'"

### ISSUE THREAD

**Issue by NikosK72** [shinnn/vscode-stylelint#196]
The latest update generates a "Error: Cannot find module 'postcss-xml'" error when opening files.

**Comment by lardissone** [comment]
I think it's a problem with stylelint issue, that was already fixed apparently: https://github.com/stylelint/stylelint/issues/3328

Please update dependencies @shinnn 
Thanks

**Comment by shinnn** [comment]
> Please update dependencies

stylelint v9.2.2 is not released yet, and,

> that was already fixed apparently

the error still happens even if you upgrade to the latest, what you call "apparently fixed", stylelint.

```sh
# ecd7c0a89ef3d0c164770883852b3574a013144e is the current latest commit of stylelint
npm i stylelint/stylelint#ecd7c0a89ef3d0c164770883852b3574a013144e
```

```js
'use strict';

const {lint} = require('stylelint');

lint({
  code: '<xml/>',
  codeFilename: 'source.xml',
  config: {
    rules: {}
  }
}).catch(console.error);
```

```console
$ node run.js
{ Error: Cannot find module 'postcss-xml'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at requireSyntax (/Users/example/node_modules/postcss-syntax/get-syntax.js:26:19)
    at getSyntax (/Users/example/node_modules/postcss-syntax/get-syntax.js:41:10)
    at parser (/Users/example/node_modules/postcss-syntax/parser.js:37:17)
    at Object.parse (/Users/example/node_modules/postcss-syntax/parse.js:18:43)
    at new LazyResult (/Users/example/node_modules/postcss/lib/lazy-result.js:70:24)
    at Processor.process (/Users/example/node_modules/postcss/lib/processor.js:117:12) code: 'MODULE_NOT_FOUND' }
```

Wait for stylelint maintainers to notice this bug, or submit a patch to https://github.com/stylelint/stylelint/pulls to fix this bug by yourself.
