### ISSUE TITLE
Error: Cannot find module 'postcss-twig' thrown when opening *.twig files

### ISSUE THREAD

**Issue by AndisGrossteins** [shinnn/vscode-stylelint#225]
I'm getting the following error with stack trace when editing *.twig (and *.html.twig) files:
```
Error: Cannot find module 'postcss-twig'
     at Function.Module._resolveFilename (module.js:470:15)
     at Function.Module._load (module.js:418:25)
     at Module.require (module.js:498:17)
     at require (internal/module.js:20:19)
     at requireSyntax (C:\Users\Andis\.vscode\extensions\shinnn.stylelint-0.37.0\node_modules\postcss-syntax\get-syntax.js:31:19)
     at getSyntax (C:\Users\Andis\.vscode\extensions\shinnn.stylelint-0.37.0\node_modules\postcss-syntax\get-syntax.js:50:10)
     at parser (C:\Users\Andis\.vscode\extensions\shinnn.stylelint-0.37.0\node_modules\postcss-syntax\parser.js:37:17)
     at Object.parse (C:\Users\Andis\.vscode\extensions\shinnn.stylelint-0.37.0\node_modules\postcss-syntax\parse.js:19:43)
     at new LazyResult (C:\Users\Andis\.vscode\extensions\shinnn.stylelint-0.37.0\node_modules\postcss\lib\lazy-result.js:70:24)
     at Processor.process (C:\Users\Andis\.vscode\extensions\shinnn.stylelint-0.37.0\node_modules\postcss\lib\processor.js:117:12)
```

As far as I can tell, there is no `postcss-twig` syntax module for postcss. At first, I thought this is related to stylelint/stylelint#3323 issue but their code is not involved in this judging by the stack trace.

This thing gets a bit more confusing because *.twig files are treated as language ID `html` which is assigned by [Twig Language](https://marketplace.visualstudio.com/items?itemName=mblode.twig-language) extension. Author of the Twig Language extension (@mblode) has described his rationale behind the decision [in this comment](https://github.com/mblode/vscode-twig-language/issues/7#issuecomment-349174484) and I agree with him.
Because of that, vscode-stylelint is invoked for HTML language according to `activationEvents` option in package.json but then postcss-syntax determines language from file extension and fails to find the non-existent `postcss-twig` syntax module.

In an attempt to avoid the error message I've added `**/*.twig` to the `ignoreFiles` option in `.stylelintrc.json` since I don't use any inline stylesheets in twig files:
```JSON
{
    "extends": "stylelint-config-recommended",
    "ignoreFiles": [ "**/*.min.css", "**/*.twig" ]
}
```

That solved the notification popping up when I edit *.twig files but I think it's still worth reporting and should be investigated for possible solutions.

Version details:
OS: Windows 10 Version 1803 build 17134.112
VSCode: 1.24.1
shinnn.vscode-stylelint: 0.37.0
mblode.twig-language: 0.2.9
stylelint (global install): 9.3.0

**Comment by shinnn** [comment]
Then [postcss-syntax](https://github.com/gucong3000/postcss-syntax) should suppress this kind of errors. Submit a new issue to https://github.com/gucong3000/postcss-syntax.
