### ISSUE TITLE
postcss-syntax fails to load a PostCSS syntax for .liquid files

### ISSUE THREAD

**Issue by ConduciveMammal** [shinnn/vscode-stylelint#227]
For a while, I've been getting this error on both Mac and Windows systems, not too sure what's causing it?

```
Error: Cannot find module 'postcss-liquid' at Function.Module._resolveFilename (module.js:470:15) at Function.Module._load (module.js:418:25) at Module.require (module.js:498:17) at require (internal/module.js:20:19) at requireSyntax (/Users/Liam/.vscode/extensions/shinnn.stylelint-0.37.0/node_modules/postcss-syntax/get-syntax.js:31:19) at getSyntax (/Users/Liam/.vscode/extensions/shinnn.stylelint-0.37.0/node_modules/postcss-syntax/get-syntax.js:50:10) at parser (/Users/Liam/.vscode/extensions/shinnn.stylelint-0.37.0/node_modules/postcss-syntax/parser.js:37:17) at Object.parse (/Users/Liam/.vscode/extensions/shinnn.stylelint-0.37.0/node_modules/postcss-syntax/parse.js:19:43) at new LazyResult (/Users/Liam/.vscode/extensions/shinnn.stylelint-0.37.0/node_modules/postcss/lib/lazy-result.js:70:24) at Processor.process (/Users/Liam/.vscode/extensions/shinnn.stylelint-0.37.0/node_modules/postcss/lib/processor.js:117:12)
```

**Comment by shinnn** [comment]
Not a vscode-stylelint issue. Ask the maintainer of [postcss-syntax](https://github.com/gucong3000/postcss-syntax) to include `.liquid` support in https://github.com/gucong3000/postcss-syntax/pull/30.
