### ISSUE TITLE
TypeError: Cannot read property 'file' of undefined at Scope.checkBlockScopedCollisions 

### ISSUE THREAD

**Issue by mliq** [shinnn/vscode-stylelint#238]
I receive the following error upon startup as of today: (js files only are open, no css).

```
TypeError: Cannot read property 'file' of undefined at Scope.checkBlockScopedCollisions (/Users/mliquori/.vscode/extensions/shinnn.stylelint-0.38.1/node_modules/@babel/traverse/lib/scope/index.js:347:22) at Scope.registerBinding (/Users/mliquori/.vscode/extensions/shinnn.stylelint-0.38.1/node_modules/@babel/traverse/lib/scope/index.js:506:16) at Scope.registerDeclaration (/Users/mliquori/.vscode/extensions/shinnn.stylelint-0.38.1/node_modules/@babel/traverse/lib/scope/index.js:446:14) at Object.BlockScoped (/Users/mliquori/.vscode/extensions/shinnn.stylelint-0.38.1/node_modules/@babel/traverse/lib/scope/index.js:189:28) at Object.newFn (/Users/mliquori/.vscode/extensions/shinnn.stylelint-0.38.1/node_modules/@babel/traverse/lib/visitors.js:230:17) at NodePath._call (/Users/mliquori/.vscode/extensions/shinnn.stylelint-0.38.1/node_modules/@babel/traverse/lib/path/context.js:53:20) at NodePath.call (/Users/mliquori/.vscode/extensions/shinnn.stylelint-0.38.1/node...
```

**Comment by shinnn** [comment]
duplicate of https://github.com/shinnn/vscode-stylelint/issues/236
