### ISSUE TITLE
postcss-less fails to parse LESS

### ISSUE THREAD

**Issue by TheAifam5** [shinnn/vscode-stylelint#265]
Like in the title :=)

```
TypeError: Cannot read property '0' of undefined
at LessParser.atrule (/home/theaifam5/.vscode/extensions/shinnn.stylelint-0.48.0/node_modules/postcss/lib/parser.js:307:16)
at LessParser.atrule (/home/theaifam5/.vscode/extensions/shinnn.stylelint-0.48.0/node_modules/postcss-less/lib/LessParser.js:26:11)
at LessParser.mixin (/home/theaifam5/.vscode/extensions/shinnn.stylelint-0.48.0/node_modules/postcss-less/lib/LessParser.js:146:10)
at LessParser.unknownWord (/home/theaifam5/.vscode/extensions/shinnn.stylelint-0.48.0/node_modules/postcss-less/lib/LessParser.js:205:12)
at LessParser.other (/home/theaifam5/.vscode/extensions/shinnn.stylelint-0.48.0/node_modules/postcss/lib/parser.js:168:12)
at LessParser.other (/home/theaifam5/.vscode/extensions/shinnn.stylelint-0.48.0/node_modules/postcss-less/lib/LessParser.js:158:13)
at LessParser.parse (/home/theaifam5/.vscode/extensions/shinnn.stylelint-0.48.0/node_modules/postcss/lib/parser.js:77:16)
at Object.parse (/home/theaifam5/.vscode/extensions/shinnn.stylelint-0.48.0/node_modules/postcss-less/lib/index.js:11:12)
at parser (/home/theaifam5/.vscode/extensions/shinnn.stylelint-0.48.0/node_modules/postcss-syntax/parser.js:10:22)
at Object.parse (/home/theaifam5/.vscode/extensions/shinnn.stylelint-0.48.0/node_modules/postcss-syntax/parse.js:28:10)
```

Example LESS:
```
body, html {
  width: 100vw;
  height: 100vh;
}

.layout {
  height: 100%;
}
```

Happens when I type the `.` (dot) for CSS-class.

**Comment by shinnn** [comment]
Not an issue with this project.
