### ISSUE TITLE
How to fix this unknown error?

### ISSUE THREAD

**Issue by tjx666** [shinnn/vscode-stylelint#271]
Error: `severity` property of a stylelint warning must be either 'error' or 'warning', but it was 'ignore' (string). at stylelintWarningToVscodeDiagnostic (C:\Users\YuTengjing\.vscode\extensions\shinnn.stylelint-0.49.0\node_modules\stylelint-warning-to-vscode-diagnostic\index.js:40:9) at Array.map (<anonymous>) at processResults (C:\Users\YuTengjing\.vscode\extensions\shinnn.stylelint-0.49.0\node_modules\stylelint-vscode\index.js:59:18) at stylelintVSCode (C:\Users\YuTengjing\.vscode\extensions\shinnn.stylelint-0.49.0\node_modules\stylelint-vscode\index.js:144:9)

**Comment by tjx666** [comment]
I'm sorry to ask so easy problem.
I add the field "ignoreFiles" to config to solve this problem.
