### ISSUE TITLE
Error while creating a css file

### ISSUE THREAD

**Issue by svenvNL** [shinnn/vscode-stylelint#65]
I got the following error:
```
workbench.main.js:28 TypeError: Cannot read property '0' of undefined     at Parser.decl (C:\Users\svenv\.vscode\extensions\shinnn.stylelint-0.23.0\node_modules\postcss\lib\parser.js:203:25)     at Parser.other (C:\Users\svenv\.vscode\extensions\shinnn.stylelint-0.23.0\node_modules\postcss\lib\parser.js:170:18)     at Parser.loop (C:\Users\svenv\.vscode\extensions\shinnn.stylelint-0.23.0\node_modules\postcss\lib\parser.js:81:26)     at parse (C:\Users\svenv\.vscode\extensions\shinnn.stylelint-0.23.0\node_modules\postcss\lib\parse.js:26:16)     at new LazyResult (C:\Users\svenv\.vscode\extensions\shinnn.stylelint-0.23.0\node_modules\postcss\lib\lazy-result.js:70:24)     at Processor.process (C:\Users\svenv\.vscode\extensions\shinnn.stylelint-0.23.0\node_modules\postcss\lib\processor.js:117:12)     at getCode.then.e (C:\Users\svenv\.vscode\extensions\shinnn.stylelint-0.23.0\node_modules\stylelint\lib\getPostcssResult.js:81:29)e.doShow @ workbench.main.js:28
```

The error occured when I did the following:
1. Created a new file theme.css
2. type the following:
```
:root
```

I got the above message in a message banner and it is in the DevTools console.
The error seems to occur when you insert a ":" anywhere as a selector in a css file.

**Comment by shinnn** [comment]
This is a bug of the upstream [stylelint](https://github.com/stylelint/stylelint) project.

```javascript
'use strict';

const stylelint = require('stylelint');

stylelint.lint({
  code: ':',
  syntax: 'scss',
  config: {
    rules: {}
  }
}).catch(err => console.error(err));
```

```
node ./example.js

TypeError: Cannot read property '0' of undefined
    at ScssParser.decl (/***/node_modules/postcss/lib/parser.js:203:25)
    at ScssParser.other (/***/node_modules/postcss/lib/parser.js:170:18)
    at ScssParser.loop (/***/node_modules/postcss/lib/parser.js:81:26)
    at scssParse (/***/node_modules/postcss-scss/lib/scss-parse.js:21:12)
    at new LazyResult (/Users/shinnn/github/vscode-stylelint/node_modules/postcss/lib/lazy-result.js:70:24)
    at Processor.process (/***/node_modules/postcss/lib/processor.js:117:12)
    at getCode.then.code (/***/node_modules/stylelint/lib/getPostcssResult.js:83:29)
```

In this case, `stylelint.lint()` must be rejected with `CssSyntaxError` rather than `TypeError`. Open a new issue on https://github.com/stylelint/stylelint/issues instead.

**Comment by shinnn** [comment]
https://github.com/postcss/postcss-scss/issues/57#issue-220715925

> Hello,
> 
> Everything is explained here: https://github.com/shinnn/vscode-stylelint/issues/65#issuecomment-292880983

Use your loaf.

**Comment by equinusocio** [comment]
@shinnn Why postcss-scss is related? i don't use it and i get the same error..

**Comment by plantain-00** [comment]
Can this kind of error show in the console rather than be alerted?
It is really annoying that it appears when I typed any character.

**Comment by shinnn** [comment]
Again, this is a bug of the upstream project.
