### ISSUE TITLE
Cannot read property '0' of undefined at Parser.decl

### ISSUE THREAD

**Issue by svipben** [shinnn/vscode-stylelint#66]
Hello,

I get this error:

`messageService.ts:126 TypeError: Cannot read property '0' of undefined     at Parser.decl (/home/svipben/.vscode/extensions/shinnn.stylelint-0.24.0/node_modules/postcss/lib/parser.js:203:25)     at Parser.other (/home/svipben/.vscode/extensions/shinnn.stylelint-0.24.0/node_modules/postcss/lib/parser.js:170:18)     at Parser.loop (/home/svipben/.vscode/extensions/shinnn.stylelint-0.24.0/node_modules/postcss/lib/parser.js:81:26)     at parse (/home/svipben/.vscode/extensions/shinnn.stylelint-0.24.0/node_modules/postcss/lib/parse.js:26:16)     at new LazyResult (/home/svipben/.vscode/extensions/shinnn.stylelint-0.24.0/node_modules/postcss/lib/lazy-result.js:70:24)     at Processor.process (/home/svipben/.vscode/extensions/shinnn.stylelint-0.24.0/node_modules/postcss/lib/processor.js:117:12)     at getCode.then.e (/home/svipben/.vscode/extensions/shinnn.stylelint-0.24.0/node_modules/stylelint/lib/getPostcssResult.js:83:29)`

`stylelint` configuration (`.stylelintrc`):

```
{
  "rules": {
    "color-no-invalid-hex": true,
    "font-family-name-quotes": "always-where-recommended",
    "font-family-no-duplicate-names": true,
    "font-weight-notation": "named-where-possible",
    "function-calc-no-unspaced-operator": true,
    "function-linear-gradient-no-nonstandard-direction": true,
    "function-max-empty-lines": 0,
    "function-url-no-scheme-relative": true,
    "function-url-quotes": "always",
    "function-whitespace-after": "always",
    "number-leading-zero": "always",
    "number-max-precision": 2,
    "number-no-trailing-zeros": true,
    "string-no-newline": true,
    "string-quotes": "single",
    "length-zero-no-unit": true,
    "time-no-imperceptible": true,
    "unit-case": "lower",
    "unit-no-unknown": true,
    "value-keyword-case": "lower",
    "value-no-vendor-prefix": true,
    "value-list-max-empty-lines": 0,
    "custom-property-empty-line-before": "never",
    "custom-property-no-outside-root": true,
    "shorthand-property-no-redundant-values": true,
    "property-case": "lower",
    "property-no-unknown": true,
    "property-no-vendor-prefix": true,
    "keyframe-declaration-no-important": true,
    "declaration-colon-space-after": "always",
    "declaration-colon-space-before": "never",
    "declaration-empty-line-before": "never",
    "declaration-no-important": true,
    "declaration-block-no-duplicate-properties": true,
    "declaration-block-no-ignored-properties": true,
    "declaration-block-no-redundant-longhand-properties": true,
    "declaration-block-no-shorthand-property-overrides": true,
    "declaration-block-semicolon-newline-after": "always",
    "declaration-block-semicolon-space-before": "never",
    "declaration-block-single-line-max-declarations": 1,
    "declaration-block-trailing-semicolon": "always",
    "block-closing-brace-empty-line-before": "never",
    "block-closing-brace-newline-after": "always",
    "block-no-empty": true,
    "selector-attribute-quotes": "always",
    "selector-combinator-space-after": "always",
    "selector-combinator-space-before": "always",
    "selector-descendant-combinator-no-non-space": true,
    "selector-max-compound-selectors": 3,
    "selector-no-attribute": true,
    "selector-no-empty": true,
    "selector-no-id": true,
    "selector-no-vendor-prefix": true,
    "selector-pseudo-class-case": "lower",
    "selector-pseudo-class-no-unknown": [
      true,
      {
        "ignorePseudoClasses": [
          "local",
          "global"
        ]
      }
    ],
    "selector-pseudo-element-case": "lower",
    "selector-pseudo-element-colon-notation": "single",
    "selector-pseudo-element-no-unknown": true,
    "selector-root-no-composition": true,
    "selector-type-case": "lower",
    "selector-type-no-unknown": true,
    "selector-max-empty-lines": 0,
    "selector-list-comma-space-after": "always",
    "selector-list-comma-space-before": "never",
    "root-no-standard-properties": true,
    "rule-nested-empty-line-before": "never-multi-line",
    "rule-non-nested-empty-line-before": "always",
    "media-feature-colon-space-after": "always",
    "media-feature-colon-space-before": "never",
    "media-feature-name-case": "lower",
    "media-feature-name-no-unknown": true,
    "media-feature-name-no-vendor-prefix": true,
    "media-feature-no-missing-punctuation": true,
    "media-feature-parentheses-space-inside": "never",
    "media-feature-range-operator-space-after": "always",
    "media-feature-range-operator-space-before": "always",
    "media-query-list-comma-space-after": "always",
    "media-query-list-comma-space-before": "never",
    "at-rule-empty-line-before": "always",
    "at-rule-name-case": "lower",
    "at-rule-name-space-after": "always",
    "at-rule-no-unknown": true,
    "at-rule-no-vendor-prefix": true,
    "at-rule-semicolon-space-before": "always",
    "at-rule-semicolon-newline-after": "always",
    "max-nesting-depth": 2,
    "no-descending-specificity": true,
    "no-duplicate-selectors": true,
    "no-extra-semicolons": true,
    "no-indistinguishable-colors": true,
    "no-invalid-double-slash-comments": true,
    "no-unknown-animations": true
  }
}
```

Latest version of Node.js, VS Code and stylelint plugin as well as stylelint.

**Comment by shinnn** [comment]
https://github.com/shinnn/vscode-stylelint/issues/65#issuecomment-292880983
